namespace: "oppa"
name: "all"
version: "0.0.1"
readme: "README.md"
authors:
    - "oleg <o-le-g@inbox.ru"
descriptions: "Collection of roles and modules to provision physical machines."
licence:
    - "MIT"
repository: "https://github.com/ol-eg/ansible"
