---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - include_vars: ../../defaults/main.yml

  - name: Collect source files stats
    stat:
      path: "/{{ item[0] }}/.{{ item[1] }}"
    register: sourced
    loop: "{{ ['root'] | product(startups) | list }}"

  - name: Verify source files have been installed
    assert:
      that:
        - sourced.results[{{ i }}].stat.path == "/{{ item[0] }}/.{{ item[1] }}"
        - sourced.results[{{ i }}].stat.mode == "0644"
        - sourced.results[{{ i }}].stat.pw_name == "{{ item[0] }}"
        - sourced.results[{{ i }}].stat.gr_name == "{{ item[0] }}"
        - sourced.results[{{ i }}].stat.size > 0
    loop: "{{ ['root'] | product(startups) | list }}"
    loop_control:
      index_var: i
...
