---
- name: Install OS prerequisites.
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ os_prerequisites }}"

- name: Install molecule
  become_user: "{{ user }}"
  pip:
    name: "{{ item }}"
    virtualenv: "{{ home }}/{{ venv_dir }}/{{ venv_name }}"
    virtualenv_command: pyvenv
  loop: "{{ py_prerequisites }}"
...
