---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - include_vars: ../../defaults/main.yml

  - name: Get vim version.
    command: vim --version
    register: ver
    changed_when: false

  - name: Verify vim version.
    assert:
      that:
        - ver.rc == 0
        - '"VIM - Vi IMproved 8" in ver.stdout'
        - '"+python3" in ver.stdout'

  - name: Read installed packages list.
    command: apt list --installed
    register: installed
    changed_when: false

  - name: Verify prerequisites are installed.
    assert:
      that: '"{{ item }}" in installed.stdout'
    loop: "{{ prerequisites }}"

  - name: Read systemwide vim config.
    command: "cat {{ sys_vimrc }}"
    register: sys_vimrc
    changed_when: false

  - name: Verify systemwide config.
    assert:
      that:
        - '"skip_defaults_vim = 1" in sys_vimrc.stdout'
        - '"set showcmd" in sys_vimrc.stdout'
        - '"set showmatch" in sys_vimrc.stdout'

  - name: Stat nerd font files.
    stat:
      path: "{{ sys_font_dir }}/nerd/{{ item }}"
    loop: "{{ fonts }}"
    register: font_files

  - name: Verify nerd fonts are installed.
    assert:
      that: "{{ item }}.stat.exists"
    loop: "{{ font_files.results }}"

  - name: Stat Vundle README.md files.
    stat:
      path: "/root/{{ vundle_dir }}/README.md"
    register: vundle_readme

  - name: Verify Vundle is installed for target user.
    assert:
      that: vundle_readme.stat.exists

  - name: Stat target user vimrc files.
    stat:
      path: "/root/.vimrc"
    register: user_vimrc

  - name: Verify target users vimrc have been created.
    assert:
      that: user_vimrc.stat.exists

  - name: Stat /usr/bin/editor.
    stat:
      path: /usr/bin/editor
    register: editor

  - name: Stat /etc/alternatives/editor.
    stat:
      path: /etc/alternatives/editor
    register: alt_editor

  - name: Verify vim is the global editor.
    assert:
      that:
        - editor.stat.exists
        - editor.stat.islnk
        - editor.stat.lnk_source == "/usr/bin/vim.nox"
        - editor.stat.lnk_target == "/etc/alternatives/editor"
...
