---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - include_vars: ../../defaults/main.yml

    - name: Read installed packages list.
      command: apt list --installed
      register: installed
      changed_when: no

    - name: Verify cruft is installed.
      assert:
        that: '"{{ package_name }}" in installed.stdout'

    - name: Stat cron.weekly/cruft.
      stat:
        path: /etc/cron.weekly/cruft
      register: cruft

    - name: Verify cruft has been scheduled.
      assert:
        that:
          - cruft.stat.pw_name == "root"
          - cruft.stat.gr_name == "root"
          - cruft.stat.mode == "0755"
          - cruft.stat.size > 0
...
