---
- name: Install shell startup files.
  copy:
    src: "{{ item[1] }}"
    dest: "{{ homedir_prefix }}/{{ item[0] }}/.{{ item[1] }}"
    group: "{{ item[0] }}"
    owner: "{{ item[0] }}"
    mode: '0644'
    backup: yes
  loop: "{{ users | product(startups) | list }}"
...
