---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - include_vars: ../../defaults/main.yml

  - name: Read installed python packages.
    shell: ". /root/{{ venv_dir }}/{{ venv_name }}/bin/activate; pip freeze"
    register: freeze
    changed_when: False

  - name: Verify molecule is installed.
    assert:
      that: '"{{ item }}==" in freeze.stdout'
    loop: "{{ py_verify }}"
...
