---
- name: Add backports to apt sources.
  apt_repository:
    repo: "{{ backports }}"
    state: present

- name: Install Tor launcher.
  apt:
    name: "{{ tor }}"
    update_cache: yes

- name: Add tor aliases to the users.
  lineinfile:
    path: "{{ homedir_prefix }}/{{ item[0] }}/.bash_aliases"
    regexp: "^{{ item[1] }}$"
    line: "{{ item[1] }}"
    create: yes
    group: "{{ item[0] }}"
    owner: "{{ item[0] }}"
    mode: '0644'
    backup: yes
  loop: "{{ users | product(tor_aliases) | list }}"
...
