---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: tst-deb-docker
    box: generic/debian10

provisioner:
  name: ansible

scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
...
