---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - include_vars: ../../defaults/main.yml

  - name: Read installed packages list.
    command: apt list --installed
    register: installed
    changed_when: false

  - name: Verify prerequisites are installed.
    assert:
      that:
        - '"{{ item }}" in installed.stdout'
    loop: "{{ prerequisites }}"

  - name: Stat ~/ansible-dev directory
    stat:
      path: "/root/{{ ansible_repo_dir }}/.git"
    register: ansible_repo

  - name: Verify ansible repository has been cloned.
    assert:
      that:
        - ansible_repo.stat.pw_name == "root"
        - ansible_repo.stat.gr_name == "root"
        - ansible_repo.stat.mode == "0755"

  - name: Get git status.
    command: git status
    args:
      chdir: "/root/{{ ansible_repo_dir }}"
    register: git_status
    changed_when: false

  - name: Verify git status.
    assert:
      that: '"On branch devel" in git_status.stdout'
...
