# This is not meant to be rock-solid installation procedure.
# (I ain't good enough with Debian, ansible etc for this).
# For me the major benefit here is the documentation as code.
# This is meant to be played straight after manual OS install,
# while host is still hooked up to the internet with the wire.
- hosts: localhost
  become: yes
  roles:
    - sys_upgrade
    # Tools to develop and test ansible roles, modules.
    # Bootstraps docker, virtualbox, and vagrant.
    - ansible_modules
    - molecule
    - bash_cfg
    - vim
